server:
  port: 8085

spring:
  application:
    name: pascoa-order-service
  datasource:
    url: jdbc:postgresql://localhost:5432/pascoa_orders
    username: postgres
    password: sua_senha
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  flyway:
    enabled: true
    locations: classpath:db/migration
  rabbitmq:
    host: localhost
    port: 5672
    username: pascoa
    password: pascoa123

auth:
  jwt:
    secret: "ALTERE-ESTA-CHAVE-SECRETA-MINIMO-32-CARACTERES-PROD"

# URLs dos serviços integrados via OpenFeign
clients:
  customer-service:
    url: http://localhost:8082
  product-service:
    url: http://localhost:8084

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    enabled: ${EUREKA_ENABLED:false}
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
