## Habilita o plugin de management e o carregamento de definições
management.load_definitions = /etc/rabbitmq/definitions.json

## Limita uso de memória a 40% da RAM alocada ao container (160 MB de 400 MB)
vm_memory_high_watermark.relative = 0.4

## Limite de disco — pausa publicações antes de esgotar disco
disk_free_limit.absolute = 512MB
