## Habilita o plugin de management e o carregamento de definições
management.load_definitions = /etc/rabbitmq/definitions.json

## Limita uso de memória do broker (≈40% do mem_limit do container)
## Substitui a variável de ambiente deprecada RABBITMQ_VM_MEMORY_HIGH_WATERMARK
vm_memory_high_watermark.relative = 0.4
